=== Eostrebis/5e.VF/Templates/json files/Race.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "eostrebis.github.io/5e.VF/Race.schema.json",
  "title": "Race",
  "description": "A choice of race in the character creator",
  "type": "object",
  "properties": {
    "ability_improvements": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "languages": {
      "type": "array",
      "items": {
        "$ref": "Language.schema.json"
      }
    },
    "size": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "speed": {
      "$ref": "Speed.schema.json"
    },
    "features": {
      "type": "array",
      "items": {
        "$ref": "Feature.schema.json"
      }
    },
    "subraces": {
      "type": "array",
      "items": {
        "$ref": "Subrace.schema.json"
      }
    }
  },
  "additionalProperties": false
}

=== Eostrebis/5e.VF/docs/races/Genasi.json
{
  "type": "Humanoïde",
  "languages": [
    {
      "type": "fix",
      "value": "Commun"
    },
    {
      "type": "fix",
      "value": "Primordial"
    }
  ],
  "size": ["S", "M"],
  "features": [
    {
      "name": "Vision dans le noir",
      "level": 1,
      "description": "Vous pouvez voir dans une lumière faible à 60 ft. comme si vous étiez dans une lumière vive, et dans l'obscurité comme si vous étiez dans une lumière faible. Vous ne discernez pas les couleurs dans une telle obscurité.",
      "darkvision": 60
    }
  ],
  "subraces": [
    {
      "name": "Genasi d'Air",
      "speed": {
        "walk": 30
      },
      "ability_improvements": "CON +2, DEX +1",
      "features": [
        {
          "name": "Souffle sans Fin",
          "level": 1,
          "description": "Vous pouvez retenir votre respiration indéfiniment tant que vous n'êtes pas incapacité."
        },
        {
          "name": "Résistance à la Foudre",
          "level": 1,
          "description": "Vous avez la résistance aux dégâts de foudre.",
          "resistances": [
            {
              "type": "fix",
              "value": "foudre"
            }
          ]
        },
        {
          "name": "Danse du Vent",
          "level": 1,
          "description": "Vous connaissez le cantrip poigne électrique. À partir du niveau 3, vous pouvez lancer le sort feuille morte avec ce trait, sans devoir payer de composantes matérielles. À partir du niveau 5, vous pouvez également lancer le sort lévitation de cette manière. Une fois que vous avez lancé feuille morte ou lévitation avec ce trait, vous ne pouvez pas le relancer tant que vous n'avez pas fini un repos long. Vous pouvez également les lancer en utilisant des emplacements de sort.\n\nL'Intelligence, la Sagesse ou le Charisme est votre caractéristique d'incantation pour ces sorts lorsque vous les lancez avec ce trait (choisi à la sélection de cette race).",
          "spells": {
            "spellcasting": {
              "type": "choice",
              "values": [
                "Intelligence",
                "Sagesse",
                "Charisme"
              ]
            },
            "0": [
              {
                "name": "poigne électrique"
              }
            ],
            "1": [
              {
                "name": "feuille morte",
                "atlevel": 3
              }
            ],
            "2": [
              {
                "name": "lévitation",
                "atlevel": 5
              }
            ]
          },
          "trackers": [
            {
              "type": "fix",
              "name": "Danse du Vent -- Feuille Morte",
              "count": 1,
              "reset": "LR"
            },
            {
              "type": "fix",
              "name": "Danse du Vent -- Lévitation",
              "count": 1,
              "reset": "LR"
            }
          ]
        }
      ]
    },
    {
      "name": "Genasi de Terre",
      "speed": {
        "walk": 30
      },
      "ability_improvements": "CON +2, FOR +1",
      "features": [
        {
          "name": "Marche Terrestre",
          "level": 1,
          "description": "Vous pouvez vous déplacer sur du terrain difficile sans dépenser de mouvement supplémentaire si vous utilisez votre vitesse de marche sur le sol."
        },
        {
          "name": "Fusion avec la Pierre",
          "level": 1,
          "description": "Vous connaissez le cantrip protection contre les armes. Vous pouvez le lancer normalement, ou en utilisant une action bonus, un nombre de fois égal à votre bonus de maîtrise par repos long.\n\nÀ partir du niveau 3, vous pouvez également lancer le sort passage sans trace de cette manière. Une fois que vous avez lancé le sort avec ce trait, vous ne pouvez pas le relancer tant que vous n'avez pas fini un repos long. Vous pouvez également le lancer en utilisant des emplacements de sort.\n\nL'Intelligence, la Sagesse ou le Charisme est votre caractéristique d'incantation pour ces sorts lorsque vous les lancez avec ce trait (choisi à la sélection de cette race).",
          "spells": {
            "spellcasting": {
              "type": "choice",
              "values": ["Intelligence", "Sagesse", "Charisme"]
            },
            "0": [
              {
                "name": "protection contre les armes"
              }
            ],
            "2": [
              {
                "name": "passage sans trace",
                "atlevel": 3
              }
            ]
          },
        "trackers": [
          {
            "name": "Fusion avec la Pierre - Protection contre les Armes",
            "type": "stat.mod",
            "count": "PB",
            "reset": "LR"
          },
          {
            "name": "Fusion avec la Pierre - Passage sans trace",
            "type": "fix",
            "count": 1,
            "reset": "LR"
          }
        ]
        }
      ]
    },
    {
      "name": "Genasi de Feu",
      "ability_improvements": "CON +2, INT +1",
      "speed": {
        "walk": 30
      },
      "features": [
        {
          "name": "Résistance au Feu",
          "level": 1,
          "description": "Vous avez la résistance aux dégâts de feu.",
          "resistances": [
            {
              "type": "fix",
              "value": "feu"
            }
          ]
        },
        {
          "name": "Embrasement",
          "level": 1,
          "description": "Vous connaissez le cantrip flammes. À partir du niveau 3, vous pouvez lancer le sort mains brûlantes avec ce trait, sans devoir payer de composantes matérielles. À partir du niveau 5, vous pouvez également lancer le sort lame de feu de cette manière. Une fois que vous avez lancé mains brûlantes ou lame de feu avec ce trait, vous ne pouvez pas le relancer tant que vous n'avez pas fini un repos long. Vous pouvez également les lancer en utilisant des emplacements de sort.\n\nL'Intelligence, la Sagesse ou le Charisme est votre caractéristique d'incantation pour ces sorts lorsque vous les lancez avec ce trait (choisi à la sélection de cette race).",
          "spells": {
            "spellcasting": {
              "type": "choice",
              "values": ["Intelligence", "Sagesse", "Charisme"]
            },
            "0": [
              {
                "name": "flammes"
              }
            ],
            "1": [
              {
                "name": "mains brûlantes",
                "atlevel": 3
              }
            ],
            "2": [
              {
                "name": "lame de feu",
                "atlevel": 5
              }
            ]
          },
          "trackers": [
            {
              "type": "fix",
              "name": "Embrasement -- Mains Brûlantes",
              "count": 1,
              "reset": "LR"
            },
            {
              "type": "fix",
              "name": "Embrasement -- Lame de Feu",
              "count": 1,
              "reset": "LR"
            }
          ]
        }
      ]
    },
    {
      "name": "Genasi d'Eau",
      "ability_improvements": "CON +2, SAG +1",
      "speed": {
        "walk": 30
      },
      "features": [
        {
          "name": "Résistance à l'Acide",
          "level": 1,
          "description": "Vous avez la résistance aux dégâts d'acide.",
          "resistances": [
            {
              "value": "acide",
              "type": "fix"
            }
          ]
        },
        {
          "name": "Amphibien",
          "level": 1,
          "description": "Vous pouvez respirer dans l'air et dans l'eau."
        },
        {
          "name": "Appel de la Vague",
          "level": 1,
          "description": "Vous connaissez le cantrip aspersion d'acide. À partir du niveau 3, vous pouvez lancer le sort création ou destruction d'eau avec ce trait, sans devoir payer de composantes matérielles. À partir du niveau 5, vous pouvez également lancer le sort marche sur l'eau de cette manière. Une fois que vous avez lancé création ou destruction d'eau ou marche sur l'eau avec ce trait, vous ne pouvez pas le relancer tant que vous n'avez pas fini un repos long. Vous pouvez également les lancer en utilisant des emplacements de sort.\n\nL'Intelligence, la Sagesse ou le Charisme est votre caractéristique d'incantation pour ces sorts lorsque vous les lancez avec ce trait (choisi à la sélection de cette race).",
          "spells": {
            "spellcasting": {
              "type": "choice",
              "values": ["Intelligence", "Sagesse", "Charisme"]
            },
            "0": [
              {
                "name": "aspersion d'acide"
              }
            ],
            "1": [
              {
                "name": "création ou destruction d'eau",
                "atlevel": 3
              }
            ],
            "2": [
              {
                "name": "marche sur l'eau",

                "atlevel": 5
              }
            ]
          },
          "trackers": [
            {
              "type": "fix",
              "name": "Appel de la Vague -- Création ou Destruction d'Eau",
              "count": 1,
              "reset": "LR"
            },
            {
              "type": "fix",
              "name": "Appel de la Vague -- Marche sur l'Eau",
              "count": 1,
              "reset": "LR"
            }
          ]

        }
      ]
    }
  ]
}

=== Eostrebis/5e.VF/docs/Races/Changelin.json
{
  "ability_improvements": "FOR +2, CHA +1",
  "type": "Fey",
  "languages": [
    {
      "type": "fix",
      "value": "Commun"
    },
    {
      "type": "choice",
      "count": 1,
      "custom": true,
      "choices": []
    }
  ],
  "size": [
    "S",
    "M"
  ],
  "speed": {
    "walk": 30
  },
  "features": [
    {
      "name": "Instincts Changelins",
      "level": 1,
      "description": "Grâce à votre connexion à la Féerie, vous maîtrisez deux des compétences suivantes : Intimidation, Intuition, Persuasion, Représentation ou Tromperie.",
      "proficiency": {
        "category": "skill",
        "type": "choice",
        "count": 1,
        "choices": [
          "Intimidation",
          "Perspicacité",
          "Persuasion",
          "Représentation",
          "Tromperie"
        ]
      }
    },
    {
      "name": "Changeforme",
      "level": 1,
      "description": "Pour une action, vous pouvez changer votre apparence et votre voix. Vous déterminez les spécifiques de ce changement, comme la couleur et la longueur des cheveux, et le genre. Vous pouvez également adapter votre taille et votre poids, et votre taille peut changer entre les catégories Petite et Moyenne. Vous pouvez vous faire apparaître comme un membre d'une autre race, même si aucune caractéristique de jeu ne changera. Vous ne pouvez pas dupliquer l'apparence d'un individu que vous n'avez jamais vu, et vous devez absolument choisir une nouvelle forme qui a la même structure squelettique que la vôtre. Vos vêtements et équipements ne sont pas modifiés par ce trait.\n\n Vous restez dans cette nouvelle forme jusqu'à ce que vous utilisiez une action pour revenir à votre vraie forme, ou que vous mourriez."
    }
  ]
}

=== Eostrebis/5e.VF/docs/races/Centaure.json
{
	"ability_improvements":"FOR +2, SAG +1",
	"type":"Fey",
	"languages":["Commun","Sylvain"],
	"size":["M"],
	"speed":{"walk":40},
	"features":[
		{"name": "Affinité Naturelle", "level": 1, "description":"Votre connexion féerique à la nature vous confère un rapport intuitif au monde naturel et aux animaux qui y habitent. Ainsi, vous maitrisez une compétence parmi les suivantes : Dressage, Médecine, Nature ou Survie.", "proficiency":{"type":"choice", "count":1, "choices":["Dressage", "Médecine", "Nature", "Survie"]}},
		{"name": "Carrure Équine", "level":1, "description":"Vous êtes considéré comme étant d'une taille supérieure à votre taille réelle lorsque vous déterminez le poids que vous pouvez porter/tirer/déplacer.\n\n De plus, escalader en utilisant vos mains et pieds est particulièrement difficile pour vous à cause de vos jambes de cheval. Ainsi, lorsque vous réalisez une telle action, chaque case de mouvement vous coûte 4 cases supplémentaires au lieu de l'unique case supplémentaire habituelle."},
		{"name": "Charge", "level":1, "description":"Si vous vous déplacez d'au moins 30 ft. en ligne droite vers une cible et la touchez avec une attaque armée de mêlée pendant le même tour, vous pouvez suivre cette attaque par une action bonus pour réaliser une seule attaque supplémentaire contre cette cible en utilisant vos sabots."},
		{"name": "Sabots", "level":1, "description":"Vous avez des sabots que vous pouvez utiliser pour réaliser des attaques non-armées. Lorsque vous touchez avec, l'attaque inflige 1d6 + votre modificateur de Force dégâts contondants plutôt que les dégâts habituels d'une attaque non-armée."}
	]
}

=== Eostrebis/5e.VF/docs/races/Fadette.json
{
  "ability_improvements": "CHA +2, DEX +1",
  "type": "Fey",
  "languages": [
    {
      "type": "fix",
      "value": "Commun"
    },
    {
      "type": "fix",
      "value": "Sylvain"
    }
  ],
  "size": ["S"],
  "speed": {
    "walk": 30
  },
  "features": [
    {
      "name": "Magie Féérique",
      "description": "Vous connaissez le cantrip druidisme. À partir du niveau 3, vous pouvez lancer le sort lueurs féériques avec ce trait. À partir du niveau 5, vous pouvez également lancer le sort agrandissement ou rapetissement de cette manière. Une fois que vous avez lancé lueurs féériques ou agrandissement ou rapetissement avec ce trait, vous ne pouvez pas le relancer tant que vous n'avez pas fini un repos long. Vous pouvez également les lancer en utilisant des emplacements de sort.",
      "spells": {
        "0": [
          {
            "name": "druidisme",
            "spellcasting": {
              "type": "choice",
              "values": ["Intelligence", "Sagesse", "Charisme"]
            }
          }
        ],
        "1": [
          {
            "name": "lueurs féériques",
            "spellcasting": {
              "type": "choice",
              "values": ["Intelligence", "Sagesse", "Charisme"]
            },
            "atlevel": 3
          }
        ],
        "2": [
          {
            "name": "agrandissement ou rapetissement",
            "spellcasting": {
              "type": "choice",
              "values": ["Intelligence", "Sagesse", "Charisme"]
            },
            "atlevel": 5
          }
        ]
      }
    },
    {
      "name": "Vol",
      "description": "Grâce à vos ailes, vous avez une vitesse de vol égale à votre vitesse de marche. Vous ne pouvez pas utiliser cette vitesse de vol si vous portez une armure moyenne ou lourde.",
      "speed": {
        "fly": "walk"
      }
    }
  ]
}

=== Eostrebis/5e.VF/races/Aasimar.json
{
  "ability_improvements": "CHA +2, SAG +1",
  "type": "Humanoïde",
  "languages": [
    {
      "type": "fix",
      "value": "Commun"
    },
    {
      "type": "fix",
      "value": "Céleste"
    }
  ],
  "size": [
    "M"
  ],
  "speed": {
    "walk": 30
  },
  "features": [
    {
      "name": "Résistance Céleste",
      "level": 1,
      "description": "Vous avez la résistance aux dégâts nécrotiques et radiant.",
      "resistances": [
        {
          "type": "fix",
          "value": "nécrotique"
        },
        {
          "type": "fix",
          "value": "radiant"
        }
      ]
    },
    {
      "name": "Vision dans le noir",
      "level": 1,
      "description": "Vous avez une vision supérieure dans l'obscurité et la lumière faible. Vous pouvez voir à 60 ft. (18 m/12 cases) dans une zone de lumière faible comme vous verriez avec une lumière vive, et dans le noir comme avec une lumière faible. Vous ne pouvez pas discerner les couleurs dans l'obscurité, seulement les nuances de gris.",
      "darkvision": 60
    },
    {
      "name": "Mains Soignantes",
      "level": 1,
      "description": "Pour une action, vous pouvez toucher une créature et lancez un nombre de d4s égal à votre modificateur de maîtrise. La créature regagne un nombre de points de vie égal au total obtenu. Une fois que vous avez utilisé ce trait, vous ne pouvez pas le réutiliser avant d'avoir fini un repos long.",
      "trackers": [
        {
          "name": "Mains Soignantes",
          "type": "fix",
          "count": 1,
          "reset": "LR"
        }
      ]
    },
    {
      "name": "Porteur de Lumière",
      "level": 1,
      "description": "Vous connaissez le cantrip Lumières. Vous utilisez le Charisme comme caractéristique d'incantation pour ce sort.",
      "spells": {
        "spellcasting": {
          "type": "fix",
          "value": "Charisme"
        },
        "0": [
          {
            "name": "Lumières"
          }
        ]
      }
    },
    {
      "name": "Révélation Céleste",
      "level": 3,
      "description": "Lorsque vous atteignez le niveau 3, choisissez l'une des révélations ci-dessous. Après cela, vous pourrez utiliser une action bonus pour libérer l'énergie céleste en vous, gagnant les bonus de cette révélation. Cette transformation dure 1 minute ou jusqu'à ce que vous la terminiez pour une action bonus. Une fois que vous vous êtes transformé en utilisant une révélation, vous ne pouvez pas le refaire jusqu'à ce que vous finissiez un repos long.",
      "trackers": [
        {
          "name": "Révélation Céleste",
          "type": "fix",
          "count": 1,
          "reset": "LR"
        }
      ],
      "choices": [
        {
          "name": "Nuage Nécrotique",
          "description": "Vos yeux deviennent brièvement des puits sombres, et de petites ailes fantomatiques apparaissent temporairement dans votre dos. Les créatures autres que vos alliés à moins de 10 ft. de vous doivent réussir un jet de sauvegarde de Charisme (DD 8 + bonus de maîtrise + modificateur de Charisme) ou être apeurées jusqu'à la fin de votre prochain tour. Jusqu'à ce que la transformation ne se termine, une fois à chacun de vos tours, vous pouvez infliger des dégâts supplémentaires nécrotiques à une cible lorsque vous lui infligez des dégâts à l'aide d'une attaque ou d'un sort. Ces dégâts supplémentaires sont égaux à votre bonus de maîtrise."
        },
        {
          "name": "Consommation Radieuse",
          "description": "Une lumière éblouissante s'échappe de vos yeux ainsi que de votre bouche. Pour la durée, vous produisez une lumière forte dans un rayon de 10 ft. et une lumière faible sur 10 ft. supplémentaires et, à la fin de chacun de vos tours, vous pouvez infliger des dégâts supplémentaires radieux à une cible lorsque vous lui infligez des dégâts à l'aide d'une attaque ou d'un sort. Ces dégâts supplémentaires sont égaux à votre bonus de maîtrise."
        },
        {
          "name": "Âme Radieuse",
          "description": "Deux ailes lumineuses et spectrales bourgeonnent temporairement de votre dos. Jusqu'à ce que la transformation ne se termine, vous possédez une vitesse de vol égale à votre vitesse de marche, et une fois par tour, vous pouvez infliger des dégâts supplémentaires radieux à une cible lorsque vous lui infligez des dégâts à l'aide d'une attaque ou d'un sort. Ces dégâts supplémentaires sont égaux à votre bonus de maîtrise."
        }
      ]
    }
  ]
}

=== Eostrebis/5e.VF/races/Filelièvre.json
{
  "ability_improvements": "DEX +2, SAG +1",
  "type": "Humanoïde",
  "languages": [
    {
      "type": "fix",
      "value": "Commun"
    },
    {
      "type": "fix",
      "value": "Sylvain"
    }
  ],
  "speed": {
    "walk": 30
  },
  "size": ["S", "M"],
  "features": [
    {
      "name": "Lever un Lièvre",
      "level": 1,
      "description": "Vous pouvez ajouter votre bonus de maîtrise à vos jets d'initiative."
    },
    {
      "name": "Sens Léporins",
      "level": 1,
      "description": "Vous maîtrisez la compétence Perception.",
      "proficiency": {
        "type": "fix",
        "category": "skill",
        "values": ["perception"]
      }
    },
    {
      "name": "Jeu de Jambes Chanceux",
      "level": 1,
      "description": "Lorsque que vous ratez un jet de sauvegarde de Dextérité, vous pouvez utiliser votre réaction pour lancer un d4 et l'ajouter au jet de sauvegarde, le transformant potentiellement en succès. Vous ne pouvez pas utiliser cette réaction si vous êtes au sol ou avec une vitesse de 0."
    },
    {
      "name": "Bond de Lapin",
      "level": 1,
      "description": "Pour une action bonus, vous pouvez sauter un nombre de ft. égal à cinq fois votre bonus de maîtrise, sans provoquer d'attaques d'opportunité. Vous ne pouvez utiliser ce trait que si votre vitesse est non nulle. Vous pouvez utiliser ce trait un nombre de fois égal à votre bonus de maîtrise, et vous récupérez toutes les utilisations en terminant un repos long.",
      "trackers": [
        {
          "name": "Bond de Lapin",
          "type": "stat.mod",
          "count": "PB",
          "reset": "LR"
        }
      ]
    }
  ]
}

=== Eostrebis/5e.VF/docs/races/Firbolg.json
{
  "ability_improvements": "FOR +2, CHA +1",
  "type": "Humanoïde",
  "languages": [
    {
      "type": "fix",
      "value": "Commun"
    },
    {
      "type": "fix",
      "value": "Primordial"
    }
  ],
  "size": ["M"],
  "speed": {
    "walk": 30
  },
  "features": [
    {
      "name": "Magie Firbolg",
      "level": 1,
      "description": "Vous pouvez lancer les sort détection de la magie et déguisement avec ce trait. Lorsque vous utilisez cette version de déguisement, vous pouvez apparaître comme 3 ft. plus grand ou plus petit. Une fois que vous avez lancé n'importe lequel de ces sorts avec ce trait, vous ne pouvez pas relancer ce sort avec ce trait tant que vous n'avez pas fini un repos long. Vous pouvez également lancer ces sorts en utilisant des emplacements de sort classiques.\n\nL'Intelligence, la Sagesse ou le Charisme est la caractéristique d'incantation pour ces sorts (vous choisissez au moment où vous sélectionnez cette race).",
      "spells": {
        "spellcasting": {
          "type": "choice",
          "values": ["Intelligence", "Sagesse", "Charisme"]
        },
        "1": [
          {
            "name": "détection de la magie"
          },
          {
            "name": "déguisement"
          }
        ]
      },
      "trackers": [
        {
          "type": "fix",
          "name": "Magie Firbolg -- Détection de la Magie",
          "count": 1,
          "reset": "LR"
        },
        {
          "type": "fix",
          "name": "Magie Firbolg -- Déguisement",
          "count": 1,
          "reset": "LR"
        }
      ]
    },
    {
      "name": "Pas Caché",
      "level": 1,
      "description": "Pour une action visible, vous pouvez magiquement devenir [[invisible]] jusqu'à la fin de votre prochain tour, ou jusqu'à ce que vous attaquiez, réalisiez un jet de dégâts, ou forciez quelqu'un à réaliser un jet de sauvegarde. Vous pouvez utiliser ce trait un nombre de fois égal à votre bonus de maîtrise, et vous regagnez toutes les utilisations après un repos long.",
      "trackers": [
        {
          "name": "Pas Caché",
          "type": "stat.mod",
          "count": "PB",
          "reset": "LR"
        }
      ]
    },
    {
      "name": "Carrure Imposante",
      "level": 1,
      "description": "Vous êtes considéré comme d'une taille plus grande lorsque vous déterminez le poids que vous pouvez porter, tirer, soulever."
    },
    {
      "name": "Dialogue de la Bête et de la Feuille",
      "level": 1,
      "description": "Vous avez la capacité de communiquer légèrement avec les Bêtes, Plantes et la végétation. Ils peuvent comprendre le sens de vos mots, même si vous n'avez pas de disposition particulière à les comprendre en retour. Vous avez l'avantage à tous les jets de Charisme que vous réalisez pour les influencer."
    }
  ]
}
